meta_product_name: "Tube2Trail"
<<<<<<< HEAD
meta_title: "Tube2Trail - Your Adventure Awaits"
meta_description: "Tube2Trail is your go-to app for city dwellers craving outdoor adventures. Say goodbye to workplace stress and hello to vibrant connections with like-minded outdoor enthusiasts. Discover tailored outdoor experiences, forge new friendships, and break free from the daily grind. Join Tube2Trail today and embark on unforgettable journeys from the concrete jungle to the untamed wilderness."
meta_image: "meta-image.png"
=======
 meta_title: "Tube2Trail - Match, Hike, Connect: Your Outdoor Circle Awaits"
>>>>>>> 05d2d3ee00661185e7cc0932b64d9b15080e1246
